version: '3.9'

services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80" # Listen on port 80
    restart: unless-stopped # Automatically restart the container unless stopped
