version: '3.9'

services:
  express-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000" # Listen on port 8080
    volumes:
      - uploads:/app/uploads  # Mount upload directory on /app/uploads 
    restart: unless-stopped # Automatically restart the container unless stopped
volumes:
  uploads: # Assign the uploads volume
